/*-
 * ============LICENSE_START=======================================================
 *  Copyright (C) 2018 Intel. All rights reserved.
 * ================================================================================
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * SPDX-License-Identifier: Apache-2.0
 * ============LICENSE_END=========================================================
 */

package org.onap.policy.distribution.reception.handling.sdc;


import org.onap.sdc.api.consumer.IDistributionStatusMessage;
import org.onap.sdc.utils.DistributionStatusEnum;

/**
  * Used to make up the distribution status message which to be sent back to DMAAP/SDC
  *
  */
public class DistributionStatusMessage implements IDistributionStatusMessage {
    /**Resource URL of the downloaded/deployed artifact - URL specified in the distribution notification message*/
    private String artifactURL;

    /**Unique ID of ONAP component instance (e.x INSTAR name)*/
    private String consumerID;

    /**
     * Distribution ID published in the distribution notification.<br>
     * Should be used to link the distribution status reports to the appropriate
     * distribution activation.<br>
     * Global Distribution Identifier: UUID generated by SDC per each
     * distribution activation.<br>
     * Generated UUID is compliant with RFC 4122. It is a 128-bit value
     * formatted into blocks of hexadecimal digits separated by a hyphen ("-").
     * Ex.: AA97B177-9383-4934-8543-0F91A7A02836
     */    
    private String distributionID;

    /**Download/Deployment status*/    
    private DistributionStatusEnum distributionStatus;

    /**
     * Timestamp of the distribution status report creation.<br>
     * The number of seconds that have elapsed since January 1, 1970.
     */
    private long timestamp;
    
    public DistributionStatusMessage (final String artifactUrl, final String consumerId,final String distributionId, 
                                      final DistributionStatusEnum distributionStatusEnum, final long timestampL) {
        artifactURL = artifactUrl;
        consumerID = consumerId;
        distributionID = distributionId;
        distributionStatus = distributionStatusEnum;
        timestamp = timestampL;
    }
    
    @Override
    public String getArtifactURL() {
        return artifactURL;
    }

    @Override
    public String getConsumerID() {
        return consumerID;
    }

    @Override
    public String getDistributionID() {
        return distributionID;
    }

    @Override
    public DistributionStatusEnum getStatus() {
        return distributionStatus;
    }

    @Override
    public long getTimestamp() {
        return timestamp;
    }

}
